spring.application.name=Sistema-Tramite-Documentario
server.port=8080
#Variables agregadas para funcionamiento de jsp y jstl
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Configuracion de recursos estaticos
spring.web.resources.static-locations=classpath:/webapp/

#logging.level.org.springframework=DEBUG
#logging.level.org.apache.catalina=DEBUG

# H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.data-locations=classpath:schema.sql,classpath:data.sql
spring.jpa.defer-datasource-initialization=true

# Mostrar SQL
spring.jpa.show-sql=true

saludo.bienvenida=Bienvenido

