spring.application.name=Sistema-Tramite-Documentario
server.port=8080
#Variables agregadas para funcionamiento de jsp y jstl
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Configuracion de recursos estaticos
spring.web.resources.static-locations=classpath:/webapp/

#logging.level.org.springframework=DEBUG
#logging.level.org.apache.catalina=DEBUG

saludo.bienvenida=Bienvenido

